apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sh.d.smarthotel360-sh360elite1-room101
spec:
  template:
    metadata:
      labels:
        app: sh.d.smarthotel360-sh360elite1-room101
        component: sh.d.smarthotel360-sh360elite1-room101
    spec:
      containers:
      - name: device-room
        image: needstobeset.azurecr.io/device-room:public
        imagePullPolicy: Always
        env:
        - name: HardwareId
          value: 
        - name: ManagementApiUrl
          value: 
        - name: MessageIntervalInMilliSeconds
          value: "5000"
        - name: RandomizationDelay
          value: "60000"
        - name: SasToken
          value:
        - name: StartupDelayInSeconds
          value: "0"