version: '3.4'

services:
  sh.d.smarthotel360-sh360elite1-room101:
    image: needstobeset.azurecr.io/device-room:dev
    build:
      context: .
      dockerfile: SmartHotel.Devices.RoomDevice/Dockerfile